config/routes.rb
Rails.application.routes.draw do
  resources :nitak_tables
  resources :activity_tables
  resources :studies
  resources :company_sizes
  get 'home_page/index'
  root "home_page#index"
  resources :inspections
  resources :company_statuses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/activity_tables_controller.rb
class ActivityTablesController < ApplicationController
  before_action :set_activity_table, only: %i[ show edit update destroy ]

  # GET /activity_tables or /activity_tables.json
  def index
    @activity_tables = ActivityTable.all
  end

  # GET /activity_tables/1 or /activity_tables/1.json
  def show
  end

  # GET /activity_tables/new
  def new
    @activity_table = ActivityTable.new
  end

  # GET /activity_tables/1/edit
  def edit
  end

  # POST /activity_tables or /activity_tables.json
  def create
    @activity_table = ActivityTable.new(activity_table_params)

    respond_to do |format|
      if @activity_table.save
        format.html { redirect_to activity_table_url(@activity_table), notice: "Activity table was successfully created." }
        format.json { render :show, status: :created, location: @activity_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_tables/1 or /activity_tables/1.json
  def update
    respond_to do |format|
      if @activity_table.update(activity_table_params)
        format.html { redirect_to activity_table_url(@activity_table), notice: "Activity table was successfully updated." }
        format.json { render :show, status: :ok, location: @activity_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_tables/1 or /activity_tables/1.json
  def destroy
    @activity_table.destroy

    respond_to do |format|
      format.html { redirect_to activity_tables_url, notice: "Activity table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_table
      @activity_table = ActivityTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_table_params
      params.require(:activity_table).permit(:activity, :active, :study_id)
    end
end

app/helpers/activity_tables_helper.rb
module ActivityTablesHelper
end

app/views/activity_tables/_activity_table.html.erb
<div id="<%= dom_id activity_table %>">
  <p>
    <strong>Activity:</strong>
    <%= activity_table.activity %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= activity_table.active %>
  </p>

  <p>
    <strong>Study:</strong>
    <%= activity_table.study_id %>
  </p>

</div>

app/views/activity_tables/_form.html.erb
<%= semantic_form_for @activity_table do |f| %>
  <%= f.inputs do %>
    <%= f.input :activity %>
    <%= f.input :active %>
    <%= f.input :study, as: :select, collection: CompanySize.pluck(:id), include_blank: true  %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/activity_tables/edit.html.erb
<h1>Editing activity table</h1>

<%= render "form", activity_table: @activity_table %>

<br>

<div>
  <%= link_to "Show this activity table", @activity_table %> |
  <%= link_to "Back to activity tables", activity_tables_path %>
</div>

app/views/activity_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Activity tables</h1>

<div id="activity_tables">
  <% @activity_tables.each do |activity_table| %>
    <%= render activity_table %>
    <p>
      <%= link_to "Show this activity table", activity_table %>
    </p>
  <% end %>
</div>

<%= link_to "New activity table", new_activity_table_path %>

app/views/activity_tables/new.html.erb
<h1>New activity table</h1>

<%= render "form", activity_table: @activity_table %>

<br>

<div>
  <%= link_to "Back to activity tables", activity_tables_path %>
</div>

app/views/activity_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity_table %>

<div>
  <%= link_to "Edit this activity table", edit_activity_table_path(@activity_table) %> |
  <%= link_to "Back to activity tables", activity_tables_path %>

  <%= button_to "Destroy this activity table", @activity_table, method: :delete %>
</div>