config/routes.rb
Rails.application.routes.draw do
  resources :nitak_tables
  resources :activity_tables
  resources :studies
  resources :company_sizes
  get 'home_page/index'
  root "home_page#index"
  resources :inspections
  resources :company_statuses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/nitak_tables_controller.rb
class NitakTablesController < ApplicationController
  before_action :set_nitak_table, only: %i[ show edit update destroy ]

  # GET /nitak_tables or /nitak_tables.json
  def index
    @nitak_tables = NitakTable.all
  end

  # GET /nitak_tables/1 or /nitak_tables/1.json
  def show
  end

  # GET /nitak_tables/new
  def new
    @nitak_table = NitakTable.new
  end

  # GET /nitak_tables/1/edit
  def edit
  end

  # POST /nitak_tables or /nitak_tables.json
  def create
    @nitak_table = NitakTable.new(nitak_table_params)

    respond_to do |format|
      if @nitak_table.save
        format.html { redirect_to nitak_table_url(@nitak_table), notice: "Nitak table was successfully created." }
        format.json { render :show, status: :created, location: @nitak_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nitak_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nitak_tables/1 or /nitak_tables/1.json
  def update
    respond_to do |format|
      if @nitak_table.update(nitak_table_params)
        format.html { redirect_to nitak_table_url(@nitak_table), notice: "Nitak table was successfully updated." }
        format.json { render :show, status: :ok, location: @nitak_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nitak_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nitak_tables/1 or /nitak_tables/1.json
  def destroy
    @nitak_table.destroy

    respond_to do |format|
      format.html { redirect_to nitak_tables_url, notice: "Nitak table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nitak_table
      @nitak_table = NitakTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nitak_table_params
      params.require(:nitak_table).permit(:activity_table_id, :company_status_id, :fixed_value, :yearly_value)
    end
end

app/helpers/nitak_tables_helper.rb
module NitakTablesHelper
end

app/views/nitak_tables/_form.html.erb
<%= semantic_form_for @nitak_table do |f| %>
  <%= f.inputs do %>
    <%= f.input :activity_table, as: :select, collection: ActivityTable.pluck(:activity, :id), include_blank: true  %>
    <%= f.input :company_status, as: :select, collection: CompanyStatus.pluck(:status, :id), include_blank: true  %>
    <%= f.input :fixed_value %>
    <%= f.input :yearly_value %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/nitak_tables/_nitak_table.html.erb
<div id="<%= dom_id nitak_table %>">
  <p>
    <strong>Activity table:</strong>
    <%= nitak_table.activity_table_id %>
  </p>

  <p>
    <strong>Company status:</strong>
    <%= nitak_table.company_status_id %>
  </p>

  <p>
    <strong>Fixed value:</strong>
    <%= nitak_table.fixed_value %>
  </p>

  <p>
    <strong>Yearly value:</strong>
    <%= nitak_table.yearly_value %>
  </p>

</div>

app/views/nitak_tables/edit.html.erb
<h1>Editing nitak table</h1>

<%= render "form", nitak_table: @nitak_table %>

<br>

<div>
  <%= link_to "Show this nitak table", @nitak_table %> |
  <%= link_to "Back to nitak tables", nitak_tables_path %>
</div>

app/views/nitak_tables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nitak tables</h1>

<div id="nitak_tables">
  <% @nitak_tables.each do |nitak_table| %>
    <%= render nitak_table %>
    <p>
      <%= link_to "Show this nitak table", nitak_table %>
    </p>
  <% end %>
</div>

<%= link_to "New nitak table", new_nitak_table_path %>

app/views/nitak_tables/new.html.erb
<h1>New nitak table</h1>

<%= render "form", nitak_table: @nitak_table %>

<br>

<div>
  <%= link_to "Back to nitak tables", nitak_tables_path %>
</div>

app/views/nitak_tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nitak_table %>

<div>
  <%= link_to "Edit this nitak table", edit_nitak_table_path(@nitak_table) %> |
  <%= link_to "Back to nitak tables", nitak_tables_path %>

  <%= button_to "Destroy this nitak table", @nitak_table, method: :delete %>
</div>