config/routes.rb
Rails.application.routes.draw do
  resources :nitak_tables
  resources :activity_tables
  resources :studies
  resources :company_sizes
  get 'home_page/index'
  root "home_page#index"
  resources :inspections
  resources :company_statuses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/study.rb
class Study < ApplicationRecord
  belongs_to :company_size
  has_many :activity_tables, dependent: :destroy, inverse_of: :study
  accepts_nested_attributes_for :activity_tables, allow_destroy: :true, reject_if: :all_blank
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: %i[ show edit update destroy ]

  # GET /studies or /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1 or /studies/1.json
  def show
    @real_employees = @study.foreigner.to_i + @study.saudi.to_i


    @all_employees = @study.special_foreigner.to_f + @study.special_saudis.to_f


    @percentage_special_saudis = (@study.special_saudis.to_f / @all_employees) * 100

    @nitak_tables_count = NitakTable.joins(:activity_table)
    .where(activity_tables: { activity: @study.activity_tables.first.activity })
    .count


    @nitak_tables = NitakTable.joins(:activity_table)
    .where(activity_tables: { activity: @study.activity_tables.first.activity })


    @company_status_ids = NitakTable.joins(:activity_table)
    .where(activity_tables: { activity: @study.activity_tables.first.activity })
    .pluck(:company_status_id)
    .uniq


    @company_statuses = CompanyStatus.where(id: @company_status_ids).pluck(:status)


    study_statuses = {}

    @nitak_tables.each do |nitak_table|
      study_statuses[nitak_table.id] = {
        yearly_value: nitak_table.yearly_value,
        fixed_value: nitak_table.fixed_value
      }
    end

    # Pass the variables to the view
    @study_statuses = study_statuses


  end

  # GET /studies/new
  def new
    @study = Study.new
    @study.activity_tables.build
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies or /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to study_url(@study), notice: "Study was successfully created." }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1 or /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to study_url(@study), notice: "Study was successfully updated." }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1 or /studies/1.json
  def destroy
    @study.destroy

    respond_to do |format|
      format.html { redirect_to studies_url, notice: "Study was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def study_params
      params.require(:study).permit(:branch, :company_size_id, :foreigner, :saudi, :ajier, :special_foreigner, :special_saudis, :localization_rate, :saudi_four, :saudi_three_four, :saudi_three, :visa, :saudi_disable, :adaptation, :saudi_jailed, :saudi_student, :saudi_online, :saudi_player, :saudi_loan_player, :foreigner_like_saudi, :foreigner_like_foreigner, :specialy_foreigner, :tribe_saudi, :gulf_citizen, :owner, :red_week, :uncounted_saudi, activity_tables_attributes: [:id, :activity, :active, :_destroy])
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= semantic_form_for @study, data: { controller: "nested-form", nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
  <%= f.inputs do %>
  <%# Start Custom Logic Here %>
  <template data-nested-form-target="template">
    <%= f.fields_for :activity_tables, ActivityTable.new, child_index: "NEW_RECORD" do |activity_table_fields| %>
      <%= render "studies/study_activity_table_form", f: activity_table_fields %>
    <% end %>
  </template>
  <%= f.fields_for :activity_tables do |activity_table_fields| %>
    <%= render "studies/study_activity_table_form", f: activity_table_fields %>
  <% end %>
  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="target"></div>
  <button type="button" data-action="nested-form#add">Add activity</button>
  <%# End Custom Logic %>
    <%= f.input :branch %>
    <%= f.input :company_size, as: :select, collection: CompanySize.pluck(:size, :id), include_blank: true  %>
    <%= f.input :foreigner %>
    <%= f.input :saudi %>
    <%= f.input :ajier %>
    <%= f.input :special_foreigner %>
    <%= f.input :special_saudis %>
    <%= f.input :localization_rate %>
    <%= f.input :saudi_four %>
    <%= f.input :saudi_three_four %>
    <%= f.input :saudi_three %>
    <%= f.input :visa %>
    <%= f.input :saudi_disable %>
    <%= f.input :adaptation %>
    <%= f.input :saudi_jailed %>
    <%= f.input :saudi_student %>
    <%= f.input :saudi_online %>
    <%= f.input :saudi_player %>
    <%= f.input :saudi_loan_player %>
    <%= f.input :foreigner_like_saudi %>
    <%= f.input :foreigner_like_foreigner %>
    <%= f.input :specialy_foreigner %>
    <%= f.input :tribe_saudi %>
    <%= f.input :gulf_citizen %>
    <%= f.input :owner %>
    <%= f.input :red_week %>
    <%= f.input :uncounted_saudi %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/studies/_study.html.erb
<div id="<%= dom_id study %>">

  <p>
    <strong>Activity:</strong>
    <ul>
      <% study.activity_tables.each do |activity_table| %>
        <li>
          <%= activity_table.activity %>
          <%= activity_table.active ? "✅" : "❌" %>
        </li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Branch:</strong>
    <%= study.branch %>
  </p>

  <p>
    <strong>Company size:</strong>
    <%= study.company_size_id %>
  </p>

  <p>
    <strong>Foreigner:</strong>
    <%= study.foreigner %>
  </p>

  <p>
    <strong>Saudi:</strong>
    <%= study.saudi %>
  </p>

  <p>
    <strong>Ajier:</strong>
    <%= study.ajier %>
  </p>

  <p>
    <strong>Special foreigner:</strong>
    <%= study.special_foreigner %>
  </p>

  <p>
    <strong>Special saudis:</strong>
    <%= study.special_saudis %>
  </p>

  <p>
    <strong>Localization rate:</strong>
    <%= study.localization_rate %>
  </p>

  <p>
    <strong>Saudi four:</strong>
    <%= study.saudi_four %>
  </p>

  <p>
    <strong>Saudi three four:</strong>
    <%= study.saudi_three_four %>
  </p>

  <p>
    <strong>Saudi three:</strong>
    <%= study.saudi_three %>
  </p>

  <p>
    <strong>Visa:</strong>
    <%= study.visa %>
  </p>

  <p>
    <strong>Saudi disable:</strong>
    <%= study.saudi_disable %>
  </p>

  <p>
    <strong>Adaptation:</strong>
    <%= study.adaptation %>
  </p>

  <p>
    <strong>Saudi jailed:</strong>
    <%= study.saudi_jailed %>
  </p>

  <p>
    <strong>Saudi student:</strong>
    <%= study.saudi_student %>
  </p>

  <p>
    <strong>Saudi online:</strong>
    <%= study.saudi_online %>
  </p>

  <p>
    <strong>Saudi player:</strong>
    <%= study.saudi_player %>
  </p>

  <p>
    <strong>Saudi loan player:</strong>
    <%= study.saudi_loan_player %>
  </p>

  <p>
    <strong>Foreigner like saudi:</strong>
    <%= study.foreigner_like_saudi %>
  </p>

  <p>
    <strong>Foreigner like foreigner:</strong>
    <%= study.foreigner_like_foreigner %>
  </p>

  <p>
    <strong>Specialy foreigner:</strong>
    <%= study.specialy_foreigner %>
  </p>

  <p>
    <strong>Tribe saudi:</strong>
    <%= study.tribe_saudi %>
  </p>

  <p>
    <strong>Gulf citizen:</strong>
    <%= study.gulf_citizen %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= study.owner %>
  </p>

  <p>
    <strong>Red week:</strong>
    <%= study.red_week %>
  </p>

  <p>
    <strong>Uncounted saudi:</strong>
    <%= study.uncounted_saudi %>
  </p>

</div>

app/views/studies/_study_activity_table_form.html.erb
<% if f.object %>
  <div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
    <%= f.label :activity %>
    <%= f.text_field :activity %>
    <%= f.label :active %>
    <%= f.check_box :active %>
    <button type="button" data-action="nested-form#remove">Remove activity</button>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing study</h1>

<%= render "form", study: @study %>

<br>

<div>
  <%= link_to "Show this study", @study %> |
  <%= link_to "Back to studies", studies_path %>
</div>

app/views/studies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Studies</h1>

<div id="studies">
  <% @studies.each do |study| %>
    <%= render study %>
    <p>
      <%= link_to "Show this study", study %>
    </p>
  <% end %>
</div>

<%= link_to "New study", new_study_path %>

app/views/studies/new.html.erb
<h1>New study</h1>

<%= render "form", study: @study %>

<br>

<div>
  <%= link_to "Back to studies", studies_path %>
</div>

app/views/studies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render "study_show", study: @study %>

<div>
  <%= link_to "Edit this study", edit_study_path(@study) %> |
  <%= link_to "Back to studies", studies_path %>

  <%= button_to "Destroy this study", @study, method: :delete %>
</div>