config/routes.rb
Rails.application.routes.draw do
  resources :nitak_tables
  resources :activity_tables
  resources :studies
  resources :company_sizes
  get 'home_page/index'
  root "home_page#index"
  resources :inspections
  resources :company_statuses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/company_statuses_controller.rb
class CompanyStatusesController < ApplicationController
  before_action :set_company_status, only: %i[ show edit update destroy ]

  # GET /company_statuses or /company_statuses.json
  def index
    @company_statuses = CompanyStatus.all
  end

  # GET /company_statuses/1 or /company_statuses/1.json
  def show
  end

  # GET /company_statuses/new
  def new
    @company_status = CompanyStatus.new
  end

  # GET /company_statuses/1/edit
  def edit
  end

  # POST /company_statuses or /company_statuses.json
  def create
    @company_status = CompanyStatus.new(company_status_params)

    respond_to do |format|
      if @company_status.save
        format.html { redirect_to company_status_url(@company_status), notice: "Company status was successfully created." }
        format.json { render :show, status: :created, location: @company_status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_statuses/1 or /company_statuses/1.json
  def update
    respond_to do |format|
      if @company_status.update(company_status_params)
        format.html { redirect_to company_status_url(@company_status), notice: "Company status was successfully updated." }
        format.json { render :show, status: :ok, location: @company_status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_statuses/1 or /company_statuses/1.json
  def destroy
    @company_status.destroy

    respond_to do |format|
      format.html { redirect_to company_statuses_url, notice: "Company status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_status
      @company_status = CompanyStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_status_params
      params.require(:company_status).permit(:status)
    end
end

app/helpers/company_statuses_helper.rb
module CompanyStatusesHelper
end

app/views/company_statuses/_company_status.html.erb
<div id="<%= dom_id company_status %>">
  <p>
    <strong>Status:</strong>
    <%= company_status.status %>
  </p>

</div>

app/views/company_statuses/_form.html.erb
<%= semantic_form_for @company_status do |f| %>
  <%= f.inputs do %>
    <%= f.input :status %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/company_statuses/edit.html.erb
<h1>Editing company status</h1>

<%= render "form", company_status: @company_status %>

<br>

<div>
  <%= link_to "Show this company status", @company_status %> |
  <%= link_to "Back to company statuses", company_statuses_path %>
</div>

app/views/company_statuses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Company statuses</h1>

<div id="company_statuses">
  <% @company_statuses.each do |company_status| %>
    <%= render company_status %>
    <p>
      <%= link_to "Show this company status", company_status %>
    </p>
  <% end %>
</div>

<%= link_to "New company status", new_company_status_path %>

app/views/company_statuses/new.html.erb
<h1>New company status</h1>

<%= render "form", company_status: @company_status %>

<br>

<div>
  <%= link_to "Back to company statuses", company_statuses_path %>
</div>

app/views/company_statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @company_status %>

<div>
  <%= link_to "Edit this company status", edit_company_status_path(@company_status) %> |
  <%= link_to "Back to company statuses", company_statuses_path %>

  <%= button_to "Destroy this company status", @company_status, method: :delete %>
</div>